/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sioterino.minesweeper;

import org.sioterino.minesweeper.App;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
