/*
 * This source file was generated by the Gradle 'init' task
 */
package org.sioterino.minesweeper;

import org.sioterino.minesweeper.models.ASCIIMenus;

import java.io.Console;
import java.util.Scanner;
import java.util.logging.ConsoleHandler;

public class App {
    public static void main(String[] args) {;


    }

	public static void clearConsole() {
		try {
			String os = System.getProperty("os.name").toLowerCase();

			if (os.contains("win")) {
				new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
			} else {
				new ProcessBuilder("clear").inheritIO().start().waitFor();
			}
		} catch (Exception e) {
			System.err.println("Error: " + e.getMessage());
			System.exit(1);
		}
	}
}
